name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  # 设置为你想自动部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest  # 运行在最新版本的Ubuntu虚拟环境上

    steps:
      - name: Checkout source
        uses: actions/checkout@v3  # 检出代码

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 设置你项目所使用的Python版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs  # 安装MkDocs
          pip install -r requirements.txt  # 安装其他依赖

      - name: Build MkDocs site
        run: mkdocs build  # 构建MkDocs网站

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # 将构建的站点部署到GitHub Pages
        with:
          github_token: ${{ secrets.MY_PERSONAL_TOKEN }} # 使用您创建的PAT
          publish_dir: ./site  # MkDocs的构建输出目录
